name: CI/CD SAM

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aws-sam-cli awscli

      - name: Build SAM app
        run: sam build

      - name: Package SAM template
        id: package
        run: |
          sam package \
            --s3-bucket ${{ secrets.S3_BUCKET }} \
            --output-template-file packaged.yaml

      - name: Upload packaged template
        uses: actions/upload-artifact@v3
        with:
          name: packaged-template
          path: packaged.yaml

  deploy-dev:
    needs: build-and-package
    runs-on: ubuntu-latest
    steps:
      - name: Download packaged template
        uses: actions/download-artifact@v3
        with:
          name: packaged-template

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token:     ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region:            ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Deploy to Dev
        run: |
          aws cloudformation deploy \
            --template-file packaged.yaml \
            --stack-name MyService-dev \
            --capabilities CAPABILITY_IAM \
            --parameter-overrides StageName=dev

  deploy-test:
    needs: build-and-package
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Download packaged template
        uses: actions/download-artifact@v3
        with:
          name: packaged-template

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token:     ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region:            ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Deploy to Test
        run: |
          aws cloudformation deploy \
            --template-file packaged.yaml \
            --stack-name MyService-test \
            --capabilities CAPABILITY_IAM \
            --parameter-overrides StageName=test

  deploy-prod:
    needs: build-and-package
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Download packaged template
        uses: actions/download-artifact@v3
        with:
          name: packaged-template

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token:     ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region:            ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Deploy to Prod
        run: |
          aws cloudformation deploy \
            --template-file packaged.yaml \
            --stack-name MyService-prod \
            --capabilities CAPABILITY_IAM \
            --parameter-overrides StageName=prod
