name: CI/CD SAM

# Déclenche sur chaque push vers main, et en manuel pour promotion test/prod
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Installer SAM CLI & AWS CLI
        run: |
          python -m pip install --upgrade pip
          pip install aws-sam-cli awscli

      - name: Build de l’application SAM
        run: sam build

      - name: Package SAM dans S3
        run: |
          sam package \
            --s3-bucket ${{ secrets.S3_BUCKET }} \
            --output-template-file packaged.yaml

      - name: Upload du template packagé
        uses: actions/upload-artifact@v2
        with:
          name: packaged-template
          path: packaged.yaml

  deploy-dev:
    needs: build-and-package
    runs-on: ubuntu-latest
    steps:
      - name: Télécharger le template packagé
        uses: actions/download-artifact@v2
        with:
          name: packaged-template

      - name: Configurer les credentials AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token:     ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region:            ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Déployer sur Dev
        run: |
          aws cloudformation deploy \
            --template-file packaged.yaml \
            --stack-name MyService-dev \
            --capabilities CAPABILITY_IAM \
            --parameter-overrides StageName=dev

  deploy-test:
    needs: build-and-package
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Télécharger le template packagé
        uses: actions/download-artifact@v2
        with:
          name: packaged-template

      - name: Configurer les credentials AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token:     ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region:            ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Déployer sur Test
        run: |
          aws cloudformation deploy \
            --template-file packaged.yaml \
            --stack-name MyService-test \
            --capabilities CAPABILITY_IAM \
            --parameter-overrides StageName=test

  deploy-prod:
    needs: build-and-package
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Télécharger le template packagé
        uses: actions/download-artifact@v2
        with:
          name: packaged-template

      - name: Configurer les credentials AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token:     ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region:            ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Déployer sur Prod
        run: |
          aws cloudformation deploy \
            --template-file packaged.yaml \
            --stack-name MyService-prod \
            --capabilities CAPABILITY_IAM \
            --parameter-overrides StageName=prod
